In [1]:
!pip show numpy

Name: numpy
Version: 1.21.5
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email: 
License: BSD
Location: c:\users\302-18\anaconda3\lib\site-packages
Requires: 
Required-by: xarray, tifffile, tables, statsmodels, seaborn, scipy, scikit-learn, scikit-image, PyWavelets, pyerfa, patsy, pandas, numexpr, numba, mkl-random, mkl-fft, matplotlib, imageio, imagecodecs, hvplot, holoviews, h5py, gensim, datashape, datashader, daal4py, Bottleneck, bokeh, bkcharts, astropy


In [2]:
# numpy의 핵심 요소는 ndArray

In [1]:
import numpy as np

In [6]:
import numpy as np
# ndarray : 다차원 배열

# 원소를 list로 주는 방법이 있음
a = np.array([1, 2, 3, 4, 5])   # 배열의 원소들은 한가지 자료형이어야 함
a  # > array([1, 2, 3, 4, 5])
type(a)
a.dtype.name   # > 'int32' : 정수 32bit

'int32'

In [8]:
nums = ['a', 2, 'b', 'c', True, 3.14] # list형은 여러 자료형을 넣어도 가능
nums
b = np.array(nums)
b   # > array(['a', '2', 'b', 'c', 'True', '3.14'], dtype='<U32') : 모든 원소들이 문자열이 되버림
b.dtype.name   # > 'str1024' : 문자열

'str1024'

In [11]:
a = np.array([1, 2, 3, 4, 5])
a.size
a.ndim   # 몇차원인지 확인하는 메소드
a.shape   # > (5,) : 원소 5개, size와 ndim을 합친거 같은 느낌

(5,)

In [16]:
a = np.array([
                [1, 2, 3], 
                [4, 5, 6]
            ])
a.size
a.ndim
a.shape   # > (2, 3) : 2행, 3열
a.itemsize   # > 4 : 원소 한개의 크기
a.data

In [17]:
a = np.array((
                [1,2,3],
                (4,5,6)
            ))
a

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
bool_array = np.array([True, False, False])
bool_array

array([ True, False, False])

In [20]:
float_array = np.array([1.2, 3.4, 2.712323])
float_array
float_array.dtype.name

'float64'

In [21]:
complex_array = np.array([1+2j, 3+2j, 5+2j], dtype=complex)  # 한 자료형만 담을 수 있으므로 dtype= 로 지정 가능
complex_array

array([1.+2.j, 3.+2.j, 5.+2.j])

# 함수형 프로그래밍(Functional Programming)

map() : 컬렉션 원소에 대해 특정 계산을 적용함

filter() : 컬렉션 원소에 대해 특정 원소만 필터링하여 새 집합 생성, 
            필터링 기준을 함수로 만들어서 적용

reduce() : 컬렉션 원소에 대해 계산을 수행하여 한개의 스칼라 값을 생성

lambda : 위의 함수에서 사용하는 첫번째 argument인 함수 (익명함수)

In [ ]:
nums = [1, 2, 3, 4, 5]

def add(x): return x+1

# list(map_obj)
list(map(add, nums))
     
# map_obj = map(add, nums)  
# map_obj는 add 함수를 어떻게 쓸까?
# nums의 원소 하나하나를 add()에 대입, nums의 모든 원소에 add() 적용

# dir(map_obj)   __iter__가 있다는건 반복문을 돌릴 수 있다는 뜻
# for e in map_obj:
#     print(e)

In [ ]:
def odd(x): return x%2==1  # 홀수인 경우만 return, True
filter(odd, nums)   # 필터링할 기준(함수)을 입력
# dir(filter)   # iter가 있으므로 loop가능
list(filter(odd, nums))

In [ ]:
from functools import reduce

def sub(x, y): return x+y # y에 nums가 들어가서 x에 대입되고 전부 합산
reduce(sub, nums)

In [ ]:
# lambda Expression
map(lambda x : x+1, nums)   # 람다에서는 'x+1'이 return

### 랜덤숫자로 2차원 배열 만들기

In [6]:
import random

zr = np.zeros((2,3))   # ndarray의 값들을 0으로 초기화
for row in range(2):
    for col in range(3):
        zr[row][col] = random.randint(1,9)
#       list[row,col] = random.randint(1,9)    > [][] 없이 [i,j]로 인덱싱 가능
#       ',' 는 축이 다르다는 뜻 
list

array([[5., 9., 1.],
       [4., 6., 7.]])

In [37]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [2]:
rg = range(5)   # numpy랑은 관련 없는 파이썬 표준 range
                # range object 리턴
for _ in rg:
    print(_, end=",")
    
lst = list(rg)
type(lst)

0,1,2,3,4,

list

In [3]:
np.arange(5)   # ndarray 의 원소 범위

array([0, 1, 2, 3, 4])

In [4]:
np.arange(3,6)

array([3, 4, 5])

In [7]:
a = np.arange(3, 10, 2)
type(a)

numpy.ndarray

In [8]:
np.arange(1,10, 0.8)

array([1. , 1.8, 2.6, 3.4, 4.2, 5. , 5.8, 6.6, 7.4, 8.2, 9. , 9.8])

In [15]:
a = np.arange(0,12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [16]:
a.shape

(12,)

In [21]:
a.reshape(3,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [22]:
a.shape  # > (12,) : 원본은 바뀌지 않는다. 

(12,)

In [24]:
a.reshape(2,6)
#   a.reshape(2,-1)   -1 은 알아서 계산해주는 것 

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [29]:
# 0~9 구간을 7개 수를 일정한 간격으로 추출하려면?
# linearly spaced values를 가져오는 방법


np.linspace(0,10,5, endpoint=True)   # 0~10 사이에 동일한 간격으로 7개를 가져온다
                                      # endpoint 는 10도 포함시킬건지 결정
    
np.linspace(0,10,5, endpoint=False)

array([0., 2., 4., 6., 8.])

In [32]:
np.random.random()   # 0~1 사이에 있는 임의의 실수

0.5034469424311387

In [33]:
np.random.random(3)   # 3개를 배열형태로 가지고 옴

array([0.0218287 , 0.80007994, 0.68870776])

In [34]:
np.random.random((3,3))   # (3,3) 은 shape형태

array([[0.18260355, 0.802448  , 0.2868325 ],
       [0.4485743 , 0.8492727 , 0.02126142],
       [0.41647325, 0.24172986, 0.35553539]])

In [ ]:
### ndarray 원소가 16개인 1차원 배열을 만들고

In [37]:
import random

a = np.random.random(16).reshape((4,4))
a

array([[0.7484366 , 0.52282794, 0.05874564, 0.59724835],
       [0.59335335, 0.09132413, 0.36505699, 0.74503981],
       [0.23720962, 0.14262916, 0.69780447, 0.61868296],
       [0.20430161, 0.37476227, 0.09262977, 0.70143082]])

In [41]:
a.flatten() # 다차원 배열을 1차원으로 변환, flatten : 납작하게

array([0.7484366 , 0.52282794, 0.05874564, 0.59724835, 0.59335335,
       0.09132413, 0.36505699, 0.74503981, 0.23720962, 0.14262916,
       0.69780447, 0.61868296, 0.20430161, 0.37476227, 0.09262977,
       0.70143082])

In [38]:
a.data   # <memory at 0x0000018D00021380>

In [40]:
b = a.reshape(-1, 16)
b.data   # <memory at 0x0000018D000215F0>  a와 b의 메모리 주소가 서로 틀림   0x : 16진수다

In [43]:
a = np.arange(4)
a

array([0, 1, 2, 3])

In [48]:
a1 = a + 1   # a배열의 원소 각각에 1이 더해짐

In [46]:
a + [1,1,1,1]

array([1, 2, 3, 4])

In [49]:
a, a1

(array([0, 1, 2, 3]), array([1, 2, 3, 4]))

In [50]:
a

array([0, 1, 2, 3])

In [52]:
b = a*2   # 각 원소에 *2
b

array([0, 2, 4, 6])

## Element-wise : 각 원소마다 연산이 가해지는 것

In [53]:
a * np.sin(1.2)

array([0.        , 0.93203909, 1.86407817, 2.79611726])

In [54]:
np.sin(a)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [55]:
# numpy의 함수들도 배열을 받게 되어 있음
# numpy의 핵심은 ndarray이므로

In [56]:
np.sqrt(a)   # sqrt()을 numpy에서는 유니버셜 함수라고 함   universal function

array([0.        , 1.        , 1.41421356, 1.73205081])

In [57]:
np.array([1,2,3]) * np.array([3,4,5])

array([ 3,  8, 15])

In [58]:
a = np.arange(6).reshape(2,-1)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [59]:
b = np.arange(6).reshape(3,-1)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

In [60]:
np.dot(a,b)   # dot product(내적;  Inner Product)

array([[10, 13],
       [28, 40]])

In [61]:
# dif(a)   배열 객체에도 dot(내적)이 있음
a.dot(b)   # a·b  수학적으로는 이렇게 표현

array([[10, 13],
       [28, 40]])

### 파이썬에서는 증감연산자 ++, -- 가 없음

In [62]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [63]:
a + 1

array([1, 2, 3, 4, 5])

In [64]:
a

array([0, 1, 2, 3, 4])

In [66]:
a += 1   # += 을 쓰면 원본 배열에 덮어써버림
a

array([2, 3, 4, 5, 6])

In [69]:
a -= 1
a

array([0, 1, 2, 3, 4])

In [70]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [71]:
a.sum()

10

In [73]:
a.max(), a.min(), a.mean(), a.std()   #std() : 표준편차

(4, 0, 2.0, 1.4142135623730951)

In [ ]:
# 평균(m)
# 분산(Variance) : 각원소와 평균의 차이의 제곱, 이들을 모두 합산, 그 값을 원소의 갯수로 나눔
# 표준편차(std) : 분산의 제곱근

In [124]:
b = a - a.mean()
c = b ** 2
lst = list(a)
d = c.sum() / len(lst)
d **(1/2)

1.4142135623730951

In [111]:
b.sum()

0.0

In [112]:
b

array([-2., -1.,  0.,  1.,  2.])

In [113]:
b ** 2

array([4., 1., 0., 1., 4.])

In [116]:
(b ** 2).sum()

10.0

In [120]:
b

array([-2., -1.,  0.,  1.,  2.])

In [123]:
a.std()

1.4142135623730951

In [125]:
a = np.arange(10, 16)
a

array([10, 11, 12, 13, 14, 15])

In [127]:
a[2], a[-1], a[0], a[-6]   # -1 은 마지막 인덱스

(12, 15, 10, 10)

In [128]:
a[a.size-1]

15

In [129]:
a[[1,2,3]]   # 서로 다른 기능의 [], 끝 []은 index, 안의 []은 list

array([11, 12, 13])

In [130]:
a = np.arange(1, 17).reshape(4,-1)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [134]:
for e in a:
    print(e)

[1 2 3 4]
[5 6 7 8]
[ 9 10 11 12]
[13 14 15 16]


In [ ]:
# a의 원소 e는 행

In [ ]:
for e in a:
    for i in e:
        print(i, end=" ")

In [136]:
a[1][2], a[1,2], a[[1,2]]   # [행,열]

(7,
 7,
 array([[ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]))

In [ ]:
# a[1][2] = a[1,2] -> index

# a[] 안의 [1,2] -> 1,2번 (다수개) 가지고 온다

In [138]:
a[[3,1]]

array([[13, 14, 15, 16],
       [ 5,  6,  7,  8]])

In [142]:
# fancy indexing : 인덱서 안에서 정수나 불리언 배열을 사용하여 배열의 값을 추출해내는 방법
ba = np.array([True, False, False, False, False, False, False, False, False, False, False, False, False, False, False, False])
ba = ba.reshape(4,-1)
ba

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [143]:
a[ba]

array([1])

In [144]:
a<2

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [145]:
a[a<2]

array([1])

In [146]:
a[1,2]

7

In [147]:
a[[1,2]]

array([[ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [148]:
nums = [1,2,3,4,5]
nums[0:5]

[1, 2, 3, 4, 5]

In [149]:
nums[2]

3

In [151]:
nums[::2]

[1, 3, 5]

In [152]:
a = np.arange(10,16)
a

array([10, 11, 12, 13, 14, 15])

In [153]:
a[1:5]

array([11, 12, 13, 14])

In [154]:
a[1:5:2]

array([11, 13])

In [155]:
a[::]

array([10, 11, 12, 13, 14, 15])

In [156]:
b = a[::]

In [157]:
b.data

In [158]:
nums = list(range(5))
nums

[0, 1, 2, 3, 4]

In [159]:
nums2 = nums[:]
nums2

[0, 1, 2, 3, 4]

In [160]:
nums2[0] = 5
nums2

[5, 1, 2, 3, 4]

In [161]:
nums

[0, 1, 2, 3, 4]

In [162]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [163]:
b = a[:]   # ndarray에서는 a를 슬라이싱해서 b로 가져오더라도, b를 바꾸면 a도 바뀐다
b

array([0, 1, 2, 3, 4])

In [164]:
b[0] = 5
b

array([5, 1, 2, 3, 4])

In [165]:
a

array([5, 1, 2, 3, 4])

In [168]:
A = np.arange(10,19).reshape(3,-1)
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [171]:
A[0, 1:]

array([11, 12])

In [172]:
A[0:2, 1:]

array([[11, 12],
       [14, 15]])

In [176]:
A[:,0]

array([10, 13, 16])

In [183]:
A[[0,2], 1:]

array([[11, 12],
       [17, 18]])

In [186]:
for e in A.flat:    # flat으로 행이 아닌 요소들을 추출 (변수)
    print(e, end=" ")

10 11 12 13 14 15 16 17 18 

In [187]:
for e in A.flatten():    # flatten()으로 행이 아닌 요소들을 추출 
    print(e, end=" ")

10 11 12 13 14 15 16 17 18 

In [188]:
for e in A.ravel():    # flat으로 행이 아닌 요소들을 추출
    print(e, end=" ")

10 11 12 13 14 15 16 17 18 

In [190]:
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [192]:
np.apply_along_axis(np.sum, axis=0, arr=A)   # axis=0 은 행

array([39, 42, 45])

In [195]:
np.apply_along_axis(np.max, axis=1, arr=A)   # axis=0 은 행

array([12, 15, 18])

In [198]:
sum = 0
for e in A.flat:
    if e % 2 == 1:
        sum += e
sum

56

In [206]:
sum = A[A % 2 == 1].sum()
sum

56

In [207]:
A.reshape(1,-1)

array([[10, 11, 12, 13, 14, 15, 16, 17, 18]])

In [208]:
A1 = A.reshape(1,-1)
A1.data

In [211]:
A1.shape = (3, -1)
A1

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [212]:
A1.data

In [213]:
A.transpose()   # 행과 열 값 바꾸기, 원본은 바뀌지 않음

array([[10, 13, 16],
       [11, 14, 17],
       [12, 15, 18]])

In [215]:
A

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [216]:
A = np.ones((3,3))
B = np.zeros((3,3))

In [217]:
np.vstack([A,B])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [218]:
np.hstack([A,B])

array([[1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.],
       [1., 1., 1., 0., 0., 0.]])

In [224]:
np.row_stack([[1,2,3],[4,5,6],[7,8,9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [228]:
A = np.arange(16).reshape(4,-1)
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [229]:
# 배열 쪼개기 (수직분리 / 수평분리)
(a1,a2) = np.hsplit(A, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [230]:
np.vsplit(A, 2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [231]:
np.split(A, [1,3], axis=1)

[array([[ 0],
        [ 4],
        [ 8],
        [12]]),
 array([[ 1,  2],
        [ 5,  6],
        [ 9, 10],
        [13, 14]]),
 array([[ 3],
        [ 7],
        [11],
        [15]])]

In [242]:
np.split(A, [2,3], axis=0)    # 2에서 자르고, 3에서 자른다

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15]])]

## Views, Copies

In [243]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [245]:
b = a    # data가 복사되는 것이 아닌 참조(메모리주소)만 복사됨

In [246]:
a[2] = 0

In [247]:
b

array([1, 2, 0, 4])

In [248]:
c = a[0:2]
c

array([1, 2])

In [252]:
a[0] = 5
a, c

(array([5, 2, 0, 4]), array([5, 2]))

In [253]:
c[1] = 7
c

array([5, 7])

In [254]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [255]:
b = a.copy()

In [256]:
b[0] = 5
b

array([5, 2, 3, 4])

In [257]:
a

array([1, 2, 3, 4])

In [258]:
v2 = np.array([1,2]) * np.array([3,4])
v2

array([3, 8])

In [259]:
a

array([1, 2, 3, 4])

In [260]:
a * 2   # broadcasting

array([2, 4, 6, 8])

In [261]:
a * [2,2,2,2]   # a*2 와 결과는 같음

array([2, 4, 6, 8])

In [262]:
# a * [2,1] 처럼 원소 개수가 안맞으면 오류 발생

In [264]:
np.save('saved_ndarray', a)
print('파일에 저장성공')

파일에 저장성공


In [266]:
fa = np.load('saved_ndarray.npy')
fa

array([1, 2, 3, 4])

In [272]:
# csv ( Comma Separated Values )
'''
id,value1,value2,value3
1,123,1.4,23
2,110,0.5,18
3,164,2.1,19
'''
ta = np.genfromtxt('sample.csv', delimiter=',', names=True)
ta[0]

(1., 123., 1.4, 23.)

In [273]:
type(ta), ta.ndim, ta.shape

(numpy.ndarray, 1, (3,))