In [3]:
import numpy as np

arr = np.array([1,2,3,4,5])
arr = np.delete(arr, 2)   # 2는 값이 아닌 index
arr

array([1, 2, 4, 5])

In [2]:
arr = np.array(["Alice", "Bob", "Charlie", "David", "Eric"])
arr = np.delete(arr, [0,1,2])
print(arr)

['David' 'Eric']


In [4]:
# 2차원은 축이 2개,.행은 axis=0, 열은 axis=1

In [5]:
arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
arr = np.delete(arr, [0,3], axis=1)
print(arr)

[[ 2  3]
 [ 6  7]
 [10 11]]


In [6]:
# axis 행 삭제

arr = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])
arr = np.delete(arr, 0, axis=0)
print(arr)

[[ 5  6  7  8]
 [ 9 10 11 12]]


In [7]:
# 조건문 삭제

arr = np.array([1, 1, 1, 1, 2, 3, 4])
arr = np.delete(arr, np.where(arr == 1))
print(arr)

[2 3 4]


In [ ]:
# 삭제

def delete_1(row):
    B = np.arange(16).reshape(4,-1)
    B = np.delete(B, row, axis=0)
    print(B)
    
def delete_2(row):
    global A
    A = np.delete(A, row, axis=0)
    print(A)

## 성적관리 프로그램 (ndarray CRUD 실습)
- 5명의 학쟁 성적 (학생의 이름, 번호)
- 3과목 (5행X3열의 2차원 배열)
- 1차원 배열 2개, 2차원 배열 1개
- 목록(s), 추가(a), 검색(번호로 검색, f), 수정(u), 삭제(d), 종료(x)
- 성적입력 시 : 번호 이름을 먼저 받고, 3과목 성적을 입력받아서 저장
- np.where(stid == 15) <- 15인 원소의 인덱스 리턴
- 삭제할 때는 '학생정보 삭제', '과목 삭제' 중 택1
- names, stid, subjects, scores(2차원)

In [2]:
stu_num

array([1, 2, 3, 4, 5])

In [3]:
stu_name

array(['Alice', 'Bob', 'Charlie', 'David', 'Eric'], dtype='<U7')

In [4]:
score

array([[ 70,  70,  70],
       [ 80,  80,  80],
       [ 90,  90,  90],
       [100, 100, 100],
       [110, 110, 110]])

In [1]:
import numpy as np

stu_num = np.array([1,2,3,4,5])
stu_name = np.array(["Alice", "Bob", "Charlie", "David", "Eric"])

score = np.zeros((5,3))
score

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [2]:
sum_list = [[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0]]
for row in range(5):
    sum_list[row][0] = stu_num[row]
    sum_list[row][1] = stu_name[row]
    sum_list[row][2] = score[row]
sum_list

[[1, 'Alice', array([0., 0., 0.])],
 [2, 'Bob', array([0., 0., 0.])],
 [3, 'Charlie', array([0., 0., 0.])],
 [4, 'David', array([0., 0., 0.])],
 [5, 'Eric', array([0., 0., 0.])]]

In [1]:
import numpy as np

stu_num = np.array([1,2,3,4,5])
stu_name = np.array(["Alice", "Bob", "Charlie", "David", "Eric"])

score = np.zeros((5,3))

sum_list = [[0,0,0],[0,0,0],[0,0,0],[0,0,0],[0,0,0]]
for row in range(5):
    sum_list[row][0] = stu_num[row]
    sum_list[row][1] = stu_name[row]
    sum_list[row][2] = score[row]


m_dic = {'s':'LIST', 'a':'ADD', 'f':'FIND', 'u':'UPDATE', 'd':'DELETE', 'x':'EXIT'}

def program():
    print('------------------------------------------------------------')
    m_input = input(' 메뉴 => 목록(s), 추가(a), 검색(f), 수정(u), 삭제(d), 종료(x):')
    return m_dic.get(m_input)

def print_list():
    print('------------------------------------------------------------')
    
    # sum_list = []
    # for i in range(0,len(stu_num)):
    #     sum_list.append([stu_num[i], stu_name[i], score[i]])
    
    try:
        fa = np.load('scores.npy')
        score = fa
        print('로드 성공')

        sum_list = []
        for i in range(0,len(score)):
            sum_list.append([stu_num[i], stu_name[i], score[i]])
        
        for i in sum_list:
            print(i)
    except:
        for i in sum_list:
            print(i)
    
    # for i in sum_list:
    #     print(i)
        
    print('------------------------------------------------------------')
        
def add_score():
    str_stu = input('번호 이름 : ')
    if len(str_stu.split()) != 2:
        print('입력 오류')
        return
    num,name = str_stu.split()
    
    sum_list = []
    for i in range(0,len(score)):
        sum_list.append([stu_num[i], stu_name[i], score[i]])
        
    for row in range(0,len(sum_list)):
        if sum_list[row][0] == int(num) and sum_list[row][1] == name:
            str_score = input('성적 3개 입력 : ')
            s1, s2, s3 = str_score.split()
            score[row] = np.array([s1, s2, s3])

    np.save('scores', score)
    print('파일에 저장성공')
    print('추가 성공')
    print_list()

def del_stu():
    num = input('삭제할 학생 번호 : ')
    id = input('학생정보 삭제(1) / 과목삭제(2)')
    
    global score
    global stu_num
    global stu_name
    
    sum_list = []
    for i in range(0,len(score)):
        sum_list.append([stu_num[i], stu_name[i], score[i]])
    
    if id == "1":
        stu_num = np.delete(stu_num, int(num)-1)
        stu_name = np.delete(stu_name, int(num)-1)
        score = np.delete(score, int(num)-1, axis=0)
    elif id == "2":
        score[int(num)-1] = np.array([0,0,0])
    else:
        print('잘못된 입력입니다.')

    print_list()
    
        
def search_stu():
    id = input('검색할 이름 : ')
    
    for row in range(0,len(sum_list)):
        if sum_list[row][1] == id:
            print(sum_list[row])
    
    try:
        fa = np.load('scores.npy')
        print('로드 성공')
        print(fa)
        for i in sum_list:
            print(i)
    except:
        for i in sum_list:
            print(i)
    
def update_stu():
    num = input('수정할 번호 : ')
    
    for i in range(0,len(stu_num)):
        if i == int(num)-1:
            print(sum_list[i])
            name = input('수정할 이름 : ')
            stu_name[i] = name
            str_score = input('성적 3개 입력 : ')
            s1, s2, s3 = str_score.split()
            score[i] = np.array([s1, s2, s3])
            print('수정 완료')
            
    np.save('scores', score)
    print('파일에 저장성공')
    print('추가 성공')
    
    print_list()

In [ ]:


go = True
while go:
    m = program()
    if m=='LIST':
        print_list()
    elif m=='ADD':
        add_score()
    elif m=='FIND':
        search_stu()
    elif m=='UPDATE':
        update_stu()
    elif m=='DELETE':
        del_stu()
    elif m=='EXIT':
        go = False
    else:
        print('메뉴 입력 오류')
print('프로그램 종료...')

------------------------------------------------------------


 메뉴 => 목록(s), 추가(a), 검색(f), 수정(u), 삭제(d), 종료(x): s


------------------------------------------------------------
로드 성공
[1, 'Alice', array([75., 75., 75.])]
[2, 'Bob', array([80., 80., 80.])]
[3, 'Charlie', array([0., 0., 0.])]
[4, 'David', array([0., 0., 0.])]
[5, 'Eric', array([0., 0., 0.])]
------------------------------------------------------------
------------------------------------------------------------
