- Merging : Join과 비슷함
- Concatenationg : 
- Combining : 덮어쓰는 것

In [8]:
import numpy as np
import pandas as pd
frame1 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
                        'price': [12.33,11.44,33.21,13.23,33.62]})

frame1

id  price
0     ball  12.33
1   pencil  11.44
2      pen  33.21
3      mug  13.23
4  ashtray  33.62

In [9]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
                        'color': ['white','red','red','black']})

frame2

id  color
0  pencil  white
1  pencil    red
2    ball    red
3     pen  black

## Merge로 서로 다른 DF의 행 병합
- 데이터가 쪼개져 있을 경우 하나로 통합시킬 때 유용하게 사용
- 공통된 요소를 자동으로 찾아서 매칭시켜 줌
- 공통된 요소가 없거나, 여러개이면 안됨  

### pd.merge(frame1, frame2, on='id')
- on='' 로 매칭할 요소를 지정해줘야 함
- on으로 지정된 요소는 열로 하나만 나옴

In [10]:
mframe = pd.merge(frame1, frame2)

In [20]:
frame3 = pd.DataFrame( {'id':['ball','pencil','pen','mug','ashtray'],
                        'color': ['white','red','red','black','green'],
                        'brand': ['OMG','ABC','ABC','POD','POD']})

frame3

id  color brand
0     ball  white   OMG
1   pencil    red   ABC
2      pen    red   ABC
3      mug  black   POD
4  ashtray  green   POD

In [25]:
frame2 = pd.DataFrame( {'id':['pencil','pencil','ball','pen'],
                        'brand': ['OMG','POD','ABC','POD']})

frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [22]:
pd.merge(frame3, frame2, on='brand')

id_x  color brand    id_y
0     ball  white   OMG  pencil
1   pencil    red   ABC    ball
2      pen    red   ABC    ball
3      mug  black   POD  pencil
4      mug  black   POD     pen
5  ashtray  green   POD  pencil
6  ashtray  green   POD     pen

### 컬럼명 바꾸기

In [28]:
frame2.columns = ['sid','brand']
frame2

sid brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [32]:
pd.merge(frame2, frame3, left_on='sid', right_on='id')

sid brand_x      id  color brand_y
0  pencil     OMG  pencil    red     ABC
1  pencil     POD  pencil    red     ABC
2    ball     ABC    ball  white     OMG
3     pen     POD     pen    red     ABC

### 위까지는 Inner Join

- Inner Join : 조건에 부합하는 값들만 가져오고 나머지는 버림
- Outter Join : 조건에 부합하지 않는 지정한 테이블의 다른 값들도 모두 가져옴

In [36]:
frame2.columns=['id','brand']
frame2

id brand
0  pencil   OMG
1  pencil   POD
2    ball   ABC
3     pen   POD

In [37]:
frame1

id  price
0     ball  12.33
1   pencil  11.44
2      pen  33.21
3      mug  13.23
4  ashtray  33.62

In [38]:
pd.merge(frame1, frame2, on='id', how='outer')

id  price brand
0     ball  12.33   ABC
1   pencil  11.44   OMG
2   pencil  11.44   POD
3      pen  33.21   POD
4      mug  13.23   NaN
5  ashtray  33.62   NaN

In [39]:
pd.merge(frame1, frame2, right_index=True, left_index=True)

id_x  price    id_y brand
0    ball  12.33  pencil   OMG
1  pencil  11.44  pencil   POD
2     pen  33.21    ball   ABC
3     mug  13.23     pen   POD

In [159]:
import random

df1 = pd.DataFrame( {'qua':['q1','q2','q3','q4'],
                    'team': [random.randint(1,9),random.randint(1,9),random.randint(1,9),random.randint(1,9)]})
df1.columns = ['seq','team']
df1

seq  team
0  q1     4
1  q2     5
2  q3     2
3  q4     8

In [59]:
df2 = pd.DataFrame( {'qua':['q1','q2','q3','q4'],
                    'team': [random.randint(1,9),random.randint(1,9),random.randint(1,9),random.randint(1,9)]})

df2

qua  team
0  q1     6
1  q2     8
2  q3     6
3  q4     8

In [71]:
df3 = pd.merge(df1,df2, left_on='seq', right_on='qua').drop('seq',axis=1)
df3

team_x qua  team_y
0       6  q1       6
1       2  q2       8
2       7  q3       6
3       5  q4       8

In [73]:
df3.set_index('qua')

team_x  team_y
qua                
q1        6       6
q2        2       8
q3        7       6
q4        5       8

In [81]:
df1.drop([3], axis=0, inplace=True)

KeyError: '[3] not found in axis'

In [83]:
df1

seq  team
0  q1     6
1  q2     8
2  q3     5

In [84]:
df2

qua  team
0  q1     6
1  q2     8
2  q3     6
3  q4     8

In [154]:
df3 = pd.merge(df1,df2, left_on='seq', right_on='qua', how='outer').drop('seq',axis=1)

df3

team_x qua  team_y
0     6.0  q1       6
1     8.0  q2       8
2     5.0  q3       6
3     NaN  q4       8

In [156]:
df3[df3.isnull()] = df3['team_x'].mean()

TypeError: Cannot do inplace boolean setting on mixed-types with a non np.nan value

In [180]:
df1.set_index('seq')

KeyError: "None of ['seq'] are in the columns"

In [171]:
df2 = df2.set_index('qua')

In [176]:
pd.merge(df1,df2)

team
0     8
1     8

In [188]:
df1 = df1.reset_index()

In [189]:
df2 = df2.reset_index()

In [199]:
df1

seq  team
0  q1     4
1  q2     5
2  q3     2
3  q4     8

In [197]:
df2 = df2.set_index('qua')

In [200]:
df2

team
qua      
q1      6
q2      8
q3      6
q4      8

In [194]:
pd.merge(df1,df2)

seq  team qua
0  q4     8  q2
1  q4     8  q4

In [217]:
pd.merge(df1,df2,right_index=True, left_on='seq')

seq  team_x  team_y
0  q1       4       6
1  q2       5       8
2  q3       2       6
3  q4       8       8

# 행렬 Array

In [218]:
array1 = np.arange(9).reshape((3,3))

array1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [219]:
array2 = np.arange(9).reshape((3,3))+6

array2

array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [220]:
np.concatenate([array1,array2], axis=1)

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11],
       [ 6,  7,  8, 12, 13, 14]])

In [221]:
np.concatenate([array1,array2], axis=0)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [222]:
ser1 = pd.Series(np.random.rand(4), index=[1,2,3,4])
ser2 = pd.Series(np.random.rand(4), index=[5,6,7,8])

In [223]:
pd.concat([ser1,ser2])

1    0.967481
2    0.022136
3    0.126316
4    0.464048
5    0.707642
6    0.576529
7    0.013180
8    0.132172
dtype: float64

# Combining

In [224]:
ser1 = pd.Series(np.random.rand(5),index=[1,2,3,4,5])   # 값 5개
ser2 = pd.Series(np.random.rand(4),index=[2,4,5,6])     # 값 4개

In [227]:
ser1

1    0.828364
2    0.419923
3    0.046945
4    0.743968
5    0.253575
dtype: float64

In [228]:
ser2

2    0.321642
4    0.776536
5    0.778642
6    0.956898
dtype: float64

In [225]:
ser1.combine_first(ser2)   # ser2 보다 ser1을 우선으로 콤바인

1    0.828364
2    0.419923
3    0.046945
4    0.743968
5    0.253575
6    0.956898
dtype: float64

In [226]:
ser2.combine_first(ser1)   # ser1 보다 ser2을 우선으로 콤바인

1    0.828364
2    0.321642
3    0.046945
4    0.776536
5    0.778642
6    0.956898
dtype: float64

In [229]:
ser1[:3].combine_first(ser2[:3])

1    0.828364
2    0.419923
3    0.046945
4    0.776536
5    0.778642
dtype: float64

# Pivoting

In [230]:
frame1 = pd.DataFrame(np.arange(9).reshape(3,3),
                      index=['white','black','red'],
                       columns=['ball','pen','pencil'])
frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [231]:
ser5 = frame1.stack()

ser5

white  ball      0
       pen       1
       pencil    2
black  ball      3
       pen       4
       pencil    5
red    ball      6
       pen       7
       pencil    8
dtype: int32

In [232]:
ser5.unstack()

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [233]:
ser5.unstack(0)

white  black  red
ball        0      3    6
pen         1      4    7
pencil      2      5    8

In [234]:
longframe = pd.DataFrame({ 'color':['white','white','white',
'red','red','red',
'black','black','black'],
'item':['ball','pen','mug',
'ball','pen','mug',
'ball','pen','mug'],
'value': np.random.rand(9)})

longframe

color  item     value
0  white  ball  0.198352
1  white   pen  0.958712
2  white   mug  0.870814
3    red  ball  0.707554
4    red   pen  0.153542
5    red   mug  0.435755
6  black  ball  0.277418
7  black   pen  0.087478
8  black   mug  0.278855

In [235]:
wideframe = longframe.pivot('color','item')

wideframe

value                    
item       ball       mug       pen
color                              
black  0.277418  0.278855  0.087478
red    0.707554  0.435755  0.153542
white  0.198352  0.870814  0.958712

## Removing

In [236]:
frame1 = pd.DataFrame(np.arange(9).reshape(3,3),
 index=['white','black','red'],
 columns=['ball','pen','pencil'])

frame1

ball  pen  pencil
white     0    1       2
black     3    4       5
red       6    7       8

In [237]:
del frame1['ball']

frame1

pen  pencil
white    1       2
black    4       5
red      7       8

In [238]:
frame1.drop('white')

pen  pencil
black    4       5
red      7       8

## Removing Duplicates

In [239]:
dframe = pd.DataFrame({ 'color': ['white','white','red','red','white'],
                        'value': [2,1,3,3,2]})

dframe

color  value
0  white      2
1  white      1
2    red      3
3    red      3
4  white      2

In [240]:
dframe.duplicated()

0    False
1    False
2    False
3     True
4     True
dtype: bool

In [241]:
dframe[dframe.duplicated()]

color  value
3    red      3
4  white      2

In [248]:
dframe = pd.DataFrame({ 'n1': [random.randint(1,5),random.randint(1,5),random.randint(1,5),random.randint(1,5),random.randint(1,5),random.randint(1,5),random.randint(1,5),random.randint(1,5),random.randint(1,5),random.randint(1,5)],
                         'n2': [random.randint(1,5),random.randint(1,5),random.randint(1,5),random.randint(1,5),random.randint(1,5),random.randint(1,5),random.randint(1,5),random.randint(1,5),random.randint(1,5),random.randint(1,5)]})

dframe

n1  n2
0   2   2
1   4   1
2   1   2
3   5   3
4   5   3
5   4   2
6   5   5
7   3   1
8   1   1
9   4   4

In [249]:
dframe[dframe.duplicated()]

n1  n2
4   5   3

In [252]:
frame = pd.DataFrame({ 'item':['ball','mug','pen','pencil','ashtray'],
 'color':['white','red','green','black','yellow']})
frame

item   color
0     ball   white
1      mug     red
2      pen   green
3   pencil   black
4  ashtray  yellow

In [250]:
 prices = {
            'ball' : 5.56,
            'mug' : 4.20,
            'bottle' : 1.30,
            'scissors' : 3.41,
            'pen' : 1.30,
            'pencil' : 0.56,
            'ashtray' : 2.75
            }

In [253]:
frame['price'] = frame['item'].map(prices)

In [254]:
frame

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [255]:
reindex = {                   # 0~4가 자동으로 인덱스로 인식
            0: 'first',
            1: 'second',
            2: 'third',
            3: 'fourth',
            4: 'fifth'
           }

frame.rename(reindex)

item   color  price
first      ball   white   5.56
second      mug     red   4.20
third       pen   green   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow   2.75

## index, columns를 dict 형태로 지정하고 한꺼번에 rename

In [261]:
recolumn = {
            'item':'object',
            'price': 'value'}

frame.rename(index=reindex, columns=recolumn)

object   color  value
first      ball   white   5.56
second      mug     red   4.20
third       pen   green   1.30
fourth   pencil   black   0.56
fifth   ashtray  yellow   2.75

## index 이름 바꾸기

In [262]:
frame.rename(index={1:'first'}, columns={'item':'object'})   # index 이름 바꾸기

object   color  price
0         ball   white   5.56
first      mug     red   4.20
2          pen   green   1.30
3       pencil   black   0.56
4      ashtray  yellow   2.75

In [258]:
frame['item'].map(prices)

0    5.56
1    4.20
2    1.30
3    0.56
4    2.75
Name: item, dtype: float64

In [259]:
frame['price'] = frame['item'].map(prices)

In [260]:
frame

item   color  price
0     ball   white   5.56
1      mug     red   4.20
2      pen   green   1.30
3   pencil   black   0.56
4  ashtray  yellow   2.75

In [281]:
df = pd.DataFrame(np.random.randint(1,20,16).reshape(4,-1))

df

0   1   2   3
0  17  12  10  10
1   3   2   8  15
2   8  15  19   9
3  17  18  14  16

In [283]:
df[df%2==0] = 0

In [284]:
df

0   1   2   3
0  17   0   0   0
1   3   0   0  15
2   0  15  19   9
3  17   0   0   0

In [289]:
fruits_df = pd.DataFrame({'name':['apple','melon','orange','banana','mango']})

fruits_df

name
0   apple
1   melon
2  orange
3  banana
4   mango

In [313]:
price = {                   # 0~4가 자동으로 인덱스로 인식
            'apple' : '1000',
            'melon' : '2000',
            'orange': '3000',
            'banana': '4000',
            'mango': '5000'
           }

In [314]:
price

{'apple': '1000',
 'melon': '2000',
 'orange': '3000',
 'banana': '4000',
 'mango': '5000'}

In [315]:
fruits_df['price'] = fruits_df['name'].map(price)

In [316]:
fruits_df

name price
0   apple  1000
1   melon  2000
2  orange  3000
3  banana  4000
4   mango  5000

In [322]:
fruits_df.rename(index={0:'a', 1:'b', 2:'c', 3:'d', 4:'e'},
                columns={'name':'fruit_name','price':'fuit_price'}, inplace=True)

In [323]:
fruits_df

fruit_name fuit_price
a      apple       1000
b      melon       2000
c     orange       3000
d     banana       4000
e      mango       5000